/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.levelp.srv.person.profile.api.controller;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import ru.levelp.srv.person.profile.api.data.PersonListResponse;
import ru.levelp.srv.person.profile.api.data.PersonRole;
import ru.levelp.srv.person.profile.api.data.ProblemResponse;

import javax.validation.Valid;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import java.util.List;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-05-19T18:45:57.374415+03:00[Europe/Moscow]")
@Validated
@Api(value = "people", description = "the people API")
public interface PeopleApi {

    /**
     * GET /people
     * Returns all people found according to the search criteria.
     *
     * @param limit  Standard pagination parameter. Defines the maximum number of entries returned in the response. (optional, default to 10)
     * @param offset Standard pagination parameter. Defines the number of entries to skip before beginning to return the search results. (optional, default to 0)
     * @param email  Person&#39;s email (optional)
     * @param role   The comma-separated list of people roles to filter the search results. Only people with the given roles are provided.  (optional, default to new ArrayList&lt;&gt;())
     * @return The request has been successfully processed. The body contains the result. (status code 200)
     * or A malformed request was sent. (status code 400)
     * or Authentication is required to access the resource. (status code 401)
     * or There are no permissions to access the resource. (status code 403)
     * or A server side error occurred while processing the request. (status code 500)
     */
    @ApiOperation(value = "", nickname = "getPeople", notes = "Returns all people found according to the search criteria.", response = PersonListResponse.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The request has been successfully processed. The body contains the result.", response = PersonListResponse.class),
            @ApiResponse(code = 400, message = "A malformed request was sent.", response = ProblemResponse.class),
            @ApiResponse(code = 401, message = "Authentication is required to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 403, message = "There are no permissions to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 500, message = "A server side error occurred while processing the request.", response = ProblemResponse.class)})
    @GetMapping(
            value = "/people",
            produces = {"application/json", "application/problem+json"}
    )
    ResponseEntity<PersonListResponse> getPeople(@Min(1) @Max(1000) @ApiParam(value = "Standard pagination parameter. Defines the maximum number of entries returned in the response.", defaultValue = "10") @Valid @RequestParam(value = "limit", required = false, defaultValue = "10") Integer limit, @Min(0) @ApiParam(value = "Standard pagination parameter. Defines the number of entries to skip before beginning to return the search results.", defaultValue = "0") @Valid @RequestParam(value = "offset", required = false, defaultValue = "0") Integer offset, @Size(max = 255) @ApiParam(value = "Person's email") @Valid @RequestParam(value = "email", required = false) String email, @ApiParam(value = "The comma-separated list of people roles to filter the search results. Only people with the given roles are provided. ") @Valid @RequestParam(value = "role", required = false) List<PersonRole> role);
}
