/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.levelp.srv.person.profile.api.controller;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import ru.levelp.srv.person.profile.api.data.CreatePersonData;
import ru.levelp.srv.person.profile.api.data.PersonResponse;
import ru.levelp.srv.person.profile.api.data.ProblemResponse;

import javax.validation.Valid;
import javax.validation.constraints.Pattern;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-05-19T18:45:57.374415+03:00[Europe/Moscow]")
@Validated
@Api(value = "person", description = "the person API")
public interface PersonApi {

    /**
     * POST /person
     * Creates a new person record.
     *
     * @param createPersonData (optional)
     * @return The request has been successfully processed. The body contains the results. (status code 201)
     * or A malformed request was sent. (status code 400)
     * or Authentication is required to access the resource. (status code 401)
     * or There are no permissions to access the resource. (status code 403)
     * or A server side error occurred while processing the request. (status code 500)
     */
    @ApiOperation(value = "", nickname = "createPerson", notes = "Creates a new person record.", response = PersonResponse.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "The request has been successfully processed. The body contains the results.", response = PersonResponse.class),
            @ApiResponse(code = 400, message = "A malformed request was sent.", response = ProblemResponse.class),
            @ApiResponse(code = 401, message = "Authentication is required to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 403, message = "There are no permissions to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 500, message = "A server side error occurred while processing the request.", response = ProblemResponse.class)})
    @PostMapping(
            value = "/person",
            produces = {"application/json", "application/problem+json"},
            consumes = {"application/json"}
    )
    ResponseEntity<PersonResponse> createPerson(@ApiParam(value = "") @Valid @RequestBody(required = false) CreatePersonData createPersonData);

    /**
     * GET /person/{personId}
     * Returns profile data of the given person.
     *
     * @param personId Universally unique identifier of the person. (required)
     * @return The person profile has been successfully found. The body contains the result. (status code 200)
     * or A malformed request was sent. (status code 400)
     * or Authentication is required to access the resource. (status code 401)
     * or There are no permissions to access the resource. (status code 403)
     * or A server side error occurred while processing the request. (status code 500)
     */
    @ApiOperation(value = "", nickname = "getPerson", notes = "Returns profile data of the given person.", response = PersonResponse.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The person profile has been successfully found. The body contains the result.", response = PersonResponse.class),
            @ApiResponse(code = 400, message = "A malformed request was sent.", response = ProblemResponse.class),
            @ApiResponse(code = 401, message = "Authentication is required to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 403, message = "There are no permissions to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 500, message = "A server side error occurred while processing the request.", response = ProblemResponse.class)})
    @GetMapping(
            value = "/person/{personId}",
            produces = {"application/json", "application/problem+json"}
    )
    ResponseEntity<PersonResponse> getPerson(@Pattern(regexp = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$") @ApiParam(value = "Universally unique identifier of the person.", required = true) @PathVariable("personId") String personId);
}
