/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.levelp.srv.person.profile.api.controller;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.context.request.NativeWebRequest;
import ru.levelp.srv.person.profile.api.ApiUtil;
import ru.levelp.srv.person.profile.model.CreatePersonData;
import ru.levelp.srv.person.profile.model.PersonResponse;
import ru.levelp.srv.person.profile.model.ProblemResponse;

import javax.validation.Valid;
import javax.validation.constraints.Pattern;
import java.util.Optional;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-05-19T18:45:57.374415+03:00[Europe/Moscow]")
@Validated
@Api(value = "person", description = "the person API")
public interface PersonApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /person
     * Creates a new person record.
     *
     * @param createPersonData (optional)
     * @return The request has been successfully processed. The body contains the results. (status code 201)
     * or A malformed request was sent. (status code 400)
     * or Authentication is required to access the resource. (status code 401)
     * or There are no permissions to access the resource. (status code 403)
     * or A server side error occurred while processing the request. (status code 500)
     */
    @ApiOperation(value = "", nickname = "createPerson", notes = "Creates a new person record.", response = PersonResponse.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "The request has been successfully processed. The body contains the results.", response = PersonResponse.class),
            @ApiResponse(code = 400, message = "A malformed request was sent.", response = ProblemResponse.class),
            @ApiResponse(code = 401, message = "Authentication is required to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 403, message = "There are no permissions to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 500, message = "A server side error occurred while processing the request.", response = ProblemResponse.class)})
    @PostMapping(
            value = "/person",
            produces = {"application/json", "application/problem+json"},
            consumes = {"application/json"}
    )
    default ResponseEntity<PersonResponse> createPerson(@ApiParam(value = "") @Valid @RequestBody(required = false) CreatePersonData createPersonData) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"messengers\" : [ { \"socialNetworkId\" : \"TELEGRAM\", \"link\" : \"@VasilyPupkin\", \"personId\" : \"123e4567-e89b-12d3-a456-426655440000\", \"id\" : \"123e4567-e89b-12d3-a456-426655440000\" }, { \"socialNetworkId\" : \"TELEGRAM\", \"link\" : \"@VasilyPupkin\", \"personId\" : \"123e4567-e89b-12d3-a456-426655440000\", \"id\" : \"123e4567-e89b-12d3-a456-426655440000\" } ], \"role\" : \"LECTOR\", \"phoneNumber\" : \"+79211234567\", \"address\" : { \"city\" : \"Moscow\", \"street\" : \"Beethovenstrasse\", \"flat\" : 123, \"postalCode\" : \"123456\", \"houseNumber\" : 12, \"houseBuilding\" : 1, \"houseLetter\" : \"A\" }, \"identity\" : { \"firstName\" : \"Vasily\", \"lastName\" : \"Pupkin\", \"placeOfBirth\" : \"Moscow\", \"gender\" : \"MALE\", \"passport\" : { \"number\" : 123456, \"placeOfIssue\" : \"\", \"series\" : 1234, \"departmentCode\" : \"123-456\", \"dateOfIssue\" : \"1980-02-07T00:00:00.000+0000\" }, \"middleName\" : \"Ivanovich\", \"dateOfBirth\" : \"1980-02-07T00:00:00.000+0000\" }, \"socialNetworks\" : [ { \"socialNetworkId\" : \"LINKED_IN\", \"link\" : \"https://linkedin.com/person/VasilyPupkin\", \"personId\" : \"123e4567-e89b-12d3-a456-426655440000\", \"id\" : \"123e4567-e89b-12d3-a456-426655440000\" }, { \"socialNetworkId\" : \"LINKED_IN\", \"link\" : \"https://linkedin.com/person/VasilyPupkin\", \"personId\" : \"123e4567-e89b-12d3-a456-426655440000\", \"id\" : \"123e4567-e89b-12d3-a456-426655440000\" } ], \"id\" : \"123e4567-e89b-12d3-a456-426655440000\", \"email\" : \"person@mail.ru\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /person/{personId}
     * Returns profile data of the given person.
     *
     * @param personId Universally unique identifier of the person. (required)
     * @return The person profile has been successfully found. The body contains the result. (status code 200)
     * or A malformed request was sent. (status code 400)
     * or Authentication is required to access the resource. (status code 401)
     * or There are no permissions to access the resource. (status code 403)
     * or A server side error occurred while processing the request. (status code 500)
     */
    @ApiOperation(value = "", nickname = "getPerson", notes = "Returns profile data of the given person.", response = PersonResponse.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The person profile has been successfully found. The body contains the result.", response = PersonResponse.class),
            @ApiResponse(code = 400, message = "A malformed request was sent.", response = ProblemResponse.class),
            @ApiResponse(code = 401, message = "Authentication is required to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 403, message = "There are no permissions to access the resource.", response = ProblemResponse.class),
            @ApiResponse(code = 500, message = "A server side error occurred while processing the request.", response = ProblemResponse.class)})
    @GetMapping(
            value = "/person/{personId}",
            produces = {"application/json", "application/problem+json"}
    )
    default ResponseEntity<PersonResponse> getPerson(@Pattern(regexp = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$") @ApiParam(value = "Universally unique identifier of the person.", required = true) @PathVariable("personId") String personId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"messengers\" : [ { \"socialNetworkId\" : \"TELEGRAM\", \"link\" : \"@VasilyPupkin\", \"personId\" : \"123e4567-e89b-12d3-a456-426655440000\", \"id\" : \"123e4567-e89b-12d3-a456-426655440000\" }, { \"socialNetworkId\" : \"TELEGRAM\", \"link\" : \"@VasilyPupkin\", \"personId\" : \"123e4567-e89b-12d3-a456-426655440000\", \"id\" : \"123e4567-e89b-12d3-a456-426655440000\" } ], \"role\" : \"LECTOR\", \"phoneNumber\" : \"+79211234567\", \"address\" : { \"city\" : \"Moscow\", \"street\" : \"Beethovenstrasse\", \"flat\" : 123, \"postalCode\" : \"123456\", \"houseNumber\" : 12, \"houseBuilding\" : 1, \"houseLetter\" : \"A\" }, \"identity\" : { \"firstName\" : \"Vasily\", \"lastName\" : \"Pupkin\", \"placeOfBirth\" : \"Moscow\", \"gender\" : \"MALE\", \"passport\" : { \"number\" : 123456, \"placeOfIssue\" : \"\", \"series\" : 1234, \"departmentCode\" : \"123-456\", \"dateOfIssue\" : \"1980-02-07T00:00:00.000+0000\" }, \"middleName\" : \"Ivanovich\", \"dateOfBirth\" : \"1980-02-07T00:00:00.000+0000\" }, \"socialNetworks\" : [ { \"socialNetworkId\" : \"LINKED_IN\", \"link\" : \"https://linkedin.com/person/VasilyPupkin\", \"personId\" : \"123e4567-e89b-12d3-a456-426655440000\", \"id\" : \"123e4567-e89b-12d3-a456-426655440000\" }, { \"socialNetworkId\" : \"LINKED_IN\", \"link\" : \"https://linkedin.com/person/VasilyPupkin\", \"personId\" : \"123e4567-e89b-12d3-a456-426655440000\", \"id\" : \"123e4567-e89b-12d3-a456-426655440000\" } ], \"id\" : \"123e4567-e89b-12d3-a456-426655440000\", \"email\" : \"person@mail.ru\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
