package ru.levelp.srv.person.profile.api.data;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Problem details serialized according to RFC 7807.
 */
@ApiModel(description = "Problem details serialized according to RFC 7807.")
public class ProblemResponse {
    @JsonProperty("type")
    private String type;

    @JsonProperty("title")
    private String title;

    @JsonProperty("status")
    private String status;

    @JsonProperty("detail")
    private String detail;

    @JsonProperty("violations")
    @Valid
    private List<ViolationData> violations = null;

    public ProblemResponse type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Problem type.
     *
     * @return type
     */
    @ApiModelProperty(example = "Errors#Validation", required = true, value = "Problem type.")
    @NotNull

    @Size(max = 2048)
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public ProblemResponse title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Short, human-readable summary of the problem type.
     *
     * @return title
     */
    @ApiModelProperty(example = "You do not have enough credit", required = true, value = "Short, human-readable summary of the problem type.")
    @NotNull

    @Size(max = 255)
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ProblemResponse status(String status) {
        this.status = status;
        return this;
    }

    /**
     * The HTTP status code generated by the origin server.
     *
     * @return status
     */
    @ApiModelProperty(example = "500", required = true, value = "The HTTP status code generated by the origin server.")
    @NotNull

    @Pattern(regexp = "^[0-9]{3}$")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public ProblemResponse detail(String detail) {
        this.detail = detail;
        return this;
    }

    /**
     * Human-readable explanation specific to this occurrence of the problem.
     *
     * @return detail
     */
    @ApiModelProperty(example = "Your current balance is 30, but that costs 50.", required = true, value = "Human-readable explanation specific to this occurrence of the problem.")
    @NotNull

    @Size(max = 65535)
    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public ProblemResponse violations(List<ViolationData> violations) {
        this.violations = violations;
        return this;
    }

    public ProblemResponse addViolationsItem(ViolationData violationsItem) {
        if (this.violations == null) {
            this.violations = new ArrayList<>();
        }
        this.violations.add(violationsItem);
        return this;
    }

    /**
     * Validation constraints violated by the request.
     *
     * @return violations
     */
    @ApiModelProperty(value = "Validation constraints violated by the request.")

    @Valid

    public List<ViolationData> getViolations() {
        return violations;
    }

    public void setViolations(List<ViolationData> violations) {
        this.violations = violations;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProblemResponse problemResponse = (ProblemResponse) o;
        return Objects.equals(this.type, problemResponse.type) &&
                Objects.equals(this.title, problemResponse.title) &&
                Objects.equals(this.status, problemResponse.status) &&
                Objects.equals(this.detail, problemResponse.detail) &&
                Objects.equals(this.violations, problemResponse.violations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, title, status, detail, violations);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProblemResponse {\n");

        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
        sb.append("    violations: ").append(toIndentedString(violations)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

