version: '3.7'

services:

  person-profile-postgres:
    image: postgres:14.3
    container_name: person-profile-postgres
    hostname: person-profile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: person_profile
      POSTGRES_USER: person_profile
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_person_profile:/var/lib/postgres

  person-profile-liquibase:
    image: liquibase/liquibase:4.10
    container_name: person-profile-liquibase
    volumes:
      - ../src/main/resources/changelog/.:/liquibase/changelog
    command:
      --changeLogFile=changelog-master.yaml
      --driver=org.postgresql.Driver
      --url=jdbc:postgresql://person-profile-postgres:5432/person_profile
      --username=person_profile
      --password=password
      update
    depends_on:
      - person-profile-postgres

  person-profile:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: person-profile
    ports:
      - "8082:8082"
    environment:
      APP_PORT: 8082
      BASE_PATH: /srv-person-profile
      APP_LOGLEVEL: INFO
      LOGGING_SETTINGS_PATH: classpath:logback-spring.xml
      DB_HOST: person-profile-postgres
      DB_PORT: 5432
      DB_NAME: person_profile
      DB_USERNAME: person_profile
      DB_PASSWORD: password
    depends_on:
      - person-profile-liquibase
      - person-profile-postgres

volumes:
  postgres_data_person_profile:
